"""新增每日簽到功能

Revision ID: 3fb56e8cf361
Revises: c5e5765160e7
Create Date: 2025-09-03 07:29:55.661594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb56e8cf361'
down_revision: Union[str, None] = 'c5e5765160e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_checkins',
    sa.Column('checkin_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('checkin_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('checkin_id'),
    sa.UniqueConstraint('user_id', 'checkin_date', name='unique_user_daily_checkin')
    )
    op.drop_constraint(op.f('fk_practice_records_ai_task_id_ai_analysis_tasks'), 'practice_records', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_practice_records_ai_task_id_ai_analysis_tasks'), 'practice_records', 'ai_analysis_tasks', ['ai_task_id'], ['task_id'])
    op.drop_table('daily_checkins')
    # ### end Alembic commands ###
