"""調整練習記錄模型：新增chapter_id欄位並讓sentence_id可為空

Revision ID: e1140d34574b
Revises: 3e06700715c6
Create Date: 2025-07-21 18:37:34.809604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1140d34574b'
down_revision: Union[str, None] = '3e06700715c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_records', sa.Column('chapter_id', sa.Uuid(), nullable=False))
    op.alter_column('practice_records', 'sentence_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'practice_records', 'chapters', ['chapter_id'], ['chapter_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice_records', type_='foreignkey')
    op.alter_column('practice_records', 'sentence_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('practice_records', 'chapter_id')
    # ### end Alembic commands ###
